package cz.salmelu.contests.client;

enum MenuAction {
	MAIN_CONTESTS,
	MAIN_RELOAD,
	MAIN_RELOAD_QUIET,
	MAIN_EXIT,
	SHOW_TEAMS,
	SHOW_CONTESTANTS,
	SHOW_ONE_TEAM,
	SCORE_CATEGORY,
	UPDATE_CONTEST,
	UPDATE_DISCIPLINE,
	UPDATE_TCATEGORY,
	UPDATE_CATEGORY,
	UPDATE_TEAM,
	UPDATE_CONTESTANT;
}
